### PR TITLE
change file name to contact.html and h1 modification accordingly.

### PR DESCRIPTION
**Pull request by shahin-collaborator**
This is shahin-collaborator!
I think it's a good idea to change the name of about.html to conatct.html.
so I fixed the issue.

### CODE REVIEW

**Comment by shahinam2** [comment]
I just checked your modification. 
why did you do that?

**Comment by shahin-collaborator** [comment]
> 

Well I think it's better to start with contact page. because first of all our customers should know that we are reachable.

**Comment by shahinam2** [comment]
That's a good idea! 
Your requested is accepted.

**Review by shahinam2 — APPROVED** [review]
It's a good idea to add the contact page first.

**Pull request merged**
